#!/bin/bash

this=$(basename "$0")

this_script_dir="$(dirname "$0")"

# colors
RED="\033[0;31m"
YELLOW="\033[1;33m"
GREEN="\033[0;32m"
NO_COLOR="\033[0m"
BOLD="\033[1m"
UNDERLINE="\033[4m"

die() { echo -e "${RED}${@}${NO_COLOR}"; exit 1; }
warn() { echo -e "${YELLOW}${@}${NO_COLOR}"; }
good() { echo -e "${GREEN}${@}${NO_COLOR}"; }
run(){ echo -e "${GREEN}${*}${NO_COLOR}"; "$@"; }

GIT=$(which git)
if [[ -z "$GIT" ]]; then
    die "git is not installed"
fi

SSH=$(which ssh)
if [[ -z "$SSH" ]]; then
    die "ssh is not installed"
fi

GIT_DIR=$($GIT rev-parse --git-dir 2>/dev/null)
if [[ -z "$GIT_DIR" ]]; then
    die "$this can only be run from a git repository."
fi


CURRENT=$($GIT symbolic-ref -q HEAD || $GIT rev-parse HEAD)
CURRENT=${CURRENT#refs/heads/}

REMOTE="origin" # 暂时固定为origin

username="$($GIT config gerrit.username)"
ssh_host="$($GIT config gerrit.sshhost)"

if [[ -z "$username" ]] || [[ -z "$ssh_host" ]]; then
    die "git config gerrit.username or git config gerrit.sshhost return null value."
fi


gerrit(){ ssh -p "${ssh_host#*:}" "$username@${ssh_host%:*}" gerrit "$@"; }

gerrit "$@"

