#!/bin/bash

this=$(basename "$0")

usage(){

cat <<EOF
$this [<commit>] [--] [<path>...]
$this --cached [<commit>] [--] [<path>...]
$this <commit> <commit> [--] [<path>...]
EOF
}

THIS_ARGS="$(getopt -o 'h' --long help,cached -- "$@")"
[[ $? != "0" ]] && { echo "argument error."; return 1; };
eval set -- "$THIS_ARGS"

DIFF_ARGS=()

while :; do
    case "${1}" in
        -h|--help)
            usage
            exit 0
            ;;
        --cached)
            DIFF_ARGS+=("--cached")
            CACHED="--cached"
            shift;;
        --)
            DIFF_ARGS+=("--")
            shift
            break;;
        *) echo "unknow options"; return 1 ;;
    esac
done

DIFF_ARGS+=("$@")

git diff --name-only "${DIFF_ARGS[@]}" | grep '' | \
    while read -r filename; do
        if [[ $filename =~ \.(sh|bash)$ ]] || [[ "$(sed -ne '1{ /^#.*sh$/p }' "$filename")" ]] ; then
            python "$(dirname "$0")/check-list-diff.py" -p1 \
                --diff=<(git diff $CACHED -U0 -- "$filename") \
                --listfile=<(shellcheck --format=gcc "$filename") \
                --format='^{filename}:{lineno}:'
        fi
    done

